name: flutter_native_ui
description: "A Flutter package to make your app look fluent on all platforms."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.11.0
  macos_ui: ^2.1.9
  yaru: ^7.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  web:
  linux:
  windows:
  macos:

flutter:
  uses-material-design: true

fonts:
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto-Regular.ttf      # regular
    - asset: assets/fonts/Roboto-Bold.ttf         # bold
    - asset: assets/fonts/Roboto-Light.ttf        # light

  - family: SegoeUI
    fonts:
    - asset: assets/fonts/segoeuithis.ttf         # regular
    - asset: assets/fonts/segoeuithibd.ttf        # bold

  - family: SFPro
    fonts:
    - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF  # regular
    - asset: assets/fonts/SFPRODISPLAYBOLD.OTF    # bold
    - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF # light

  - family: Ubuntu
    fonts:
    - asset: assets/fonts/Ubuntu-Regular.ttf      # regular
    - asset: assets/fonts/Ubuntu-Bold.ttf         # bold
    - asset: assets/fonts/Ubuntu-Light.ttf        # light