name: flutter_native_ui
description: "A Flutter package to make your app look native on all platforms."
version: 0.0.0-dev1
homepage: "https://calebh101.com/applications/flutter_native_ui"
repository: "https://github.com/Calebh101/flutter_native_ui"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluent_ui: ^4.11.0
  macos_ui: ^2.1.9
  yaru: ^7.0.0
  puppeteer: ^3.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
      - asset: assets/fonts/Roboto-Regular.ttf      # regular
      - asset: assets/fonts/Roboto-Bold.ttf         # bold
      - asset: assets/fonts/Roboto-Light.ttf        # ligh$t

    - family: SegoeUI
      fonts:
      - asset: assets/fonts/segoeuithis.ttf         # regular
      - asset: assets/fonts/segoeuithibd.ttf        # bold

    - family: SFPro
      fonts:
      - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF  # regular
      - asset: assets/fonts/SFPRODISPLAYBOLD.OTF    # bold
      - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF # light

    - family: Ubuntu
      fonts:
      - asset: assets/fonts/Ubuntu-Regular.ttf      # regular
      - asset: assets/fonts/Ubuntu-Bold.ttf         # bold
      - asset: assets/fonts/Ubuntu-Light.ttf        # light
